repository: ielab/searchrefiner
timezone: AEST
# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

exclude:
    - _site/
